Usability improvements
ms-iot/ros_msft_luis pull request #28
Opened 2021-09-08 22:16 UTC by ooeygui

2021-09-08 22:21 UTC, amelhassan approved these changes

2021-09-08 23:37 UTC, lilustga commented on ros_msft_luis/launch/luis.launch
> +    <param name="luiskey" value="$(arg robotId)" />
this should be "$(arg azure_cs_luis_key)"

2021-09-08 23:38 UTC, lilustga commented on ros_msft_luis/launch/luis.launch
> +  <arg name="azure_cs_luis_endpoint" default="$(env azure_cs_luis_endpoint)"/>
This makes endpoint required to run the launch file, should it be optional?

2021-09-09 00:02 UTC, PranavDhulipala requested changes
```
    if (root_object)
    {
        // is this "topScoringIntent": "Move Arm Backward" on root?

        JSON_Object *topScoringIntent_object = json_object_dotget_object(root_object, "topScoringIntent");
        if (topScoringIntent_object)
        {
            intent.topIntent = json_object_dotget_string(topScoringIntent_object, "intent");
            if (!intent.topIntent.empty())
            {
                intent.score = (float)json_object_get_number(topScoringIntent_object, "score");

                score = intent.score;
            }
        }
        // Process the entities array
        JSON_Array *entities_array = json_object_get_array(root_object, "entities");
        if (entities_array)
        {
            size_t count = json_array_get_count(entities_array);
            for (size_t i = 0; i < count; i++)
            {
                JSON_Object *entity_object = json_array_get_object(entities_array, i);
                if (entity_object)
                {
                    std::string type = json_object_dotget_string(entity_object, "type");
                    std::string entity = json_object_dotget_string(entity_object, "entity");
                    if (type == "builtin.keyPhrase")
                    {
                        intent.dimension.unit = entity;
                    }
                    if (type == "builtin.number")
                    {
                        intent.dimension.value = std::stof(entity);
                    }
                }
            }
        }
    }
```

2021-09-24 21:01 UTC, lilustga approved these changes

2025-11-24 17:48 UTC, closed without merging