Implement move_base goals
ms-iot/ros_msft_luis pull request #31
Opened 2021-09-27 08:57 UTC by tomconte

This PR is in support of #16, in draft mode to solicit feedback. /cc @ooeygui @amelhassan 

Forward/backward movement (in meters) and right/left rotation (in degrees) are implemented.

I had to make two changes to the LUIS node itself:

- Modify `parseAndPublishFromJson()` to add the entities to the intent message (for rotation, the degrees are not recognised as a dimension, but they appear as a number entity).
- The keyword recogniser only worked once in my tests; after a successful keyword recognition it would just stop working. I now create a new recogniser at each iteration of the `ros::ok()` loop.

I am looking at adding the following:

- Support for feet (just convert feet to meters).
- Implement the STOP intent to cancel the current action, in case the robot gets lost.

2021-09-27 15:05 UTC, ooeygui requested changes

2021-09-27 15:05 UTC, ooeygui commented on ros_msft_luis/src/azure_cs_luis.cpp
> +                        } else if (type == "builtin.number") {
We like to practice "when in rome" coding style - in this case, the brace style is next line.

2021-09-27 15:05 UTC, ooeygui commented on ros_msft_luis/src/azure_cs_luis.cpp
> +                            if (resolution_object)
Can you add a comment about what case this addresses?

2021-09-27 15:05 UTC, ooeygui commented on ros_msft_luis_move_base/src/ros_msft_luis_move_base.cpp
> +std::string str_tolower(std::string s) {
brace style

2021-09-28 12:12 UTC, tomconte commented on ros_msft_luis/src/azure_cs_luis.cpp
> +                        } else if (type == "builtin.number") {
Done.

As a suggestion, we could use clang-format with a ROS config to ensure format consistency, e.g. run it on existing code and then using it in the CI pipeline to validate.

https://github.com/PickNikRobotics/roscpp_code_format

2021-09-28 12:12 UTC, tomconte commented on ros_msft_luis/src/azure_cs_luis.cpp
> +                            if (resolution_object)
Done.

2021-09-28 12:12 UTC, tomconte commented on ros_msft_luis_move_base/src/ros_msft_luis_move_base.cpp
> +std::string str_tolower(std::string s) {
👍🏻

2021-09-30 17:21 UTC, ooeygui commented
Super cool :-)

2021-09-30 17:21 UTC, merged